version: '3.8'

services:
  mysql:
    image: mysql:tag
    container_name: some-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    networks:
      - mynetwork

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge